apiVersion: v1
kind: Service
metadata:
  name: ekart-service
spec:
  selector:
    app: ekart
  ports:
  - protocol: TCP
    port: 8070       # Service port
    targetPort: 8070 # Target port in the container
  type: LoadBalancer # Use ClusterIP for internal access only or NodePort for external access without a load balancer
